### ISSUE TITLE
Commit fails if PR review requested from Team

### ISSUE THREAD

**Issue by gitbugr** [imgurbot12/prbot#1]
Hey, love the tool!

I'm getting the following when my action tries to run `prbot commit`:

```
Error: failed to clean old reviews
Caused by:
    failed to find review username
```

This occurs following the request of a review by an organisation Team in Gitea.

I believe this is the problematic line/section: https://github.com/imgurbot12/prbot/blob/d7f53126e6c9056a144dce9ef46f640b2cffc283/src/api.rs#L64 which is looking for "username" in the list of reviews, however this item has the structure:

<details>
<summary>(example item)</summary>

```json
{
    "id": 893,
    "user": null,
    "team": {
      "id": 2,
      "name": "Devs",
      "description": "",
      "organization": null,
      "includes_all_repositories": true,
      "permission": "admin",
      "units": [
        "repo.code",
        "repo.pulls",
        "repo.wiki",
        "repo.actions",
        "repo.issues",
        "repo.ext_issues",
        "repo.releases",
        "repo.ext_wiki",
        "repo.projects",
        "repo.packages"
      ],
      "units_map": {
        "repo.actions": "admin",
        "repo.code": "admin",
        "repo.ext_issues": "admin",
        "repo.ext_wiki": "admin",
        "repo.issues": "admin",
        "repo.packages": "admin",
        "repo.projects": "admin",
        "repo.pulls": "admin",
        "repo.releases": "admin",
        "repo.wiki": "admin"
      },
      "can_create_org_repo": true
    },
    "state": "REQUEST_REVIEW",
    "body": "",
    "commit_id": "",
    "stale": true,
    "official": false,
    "dismissed": false,
    "comments_count": 0,
    "submitted_at": "2024-10-31T00:00:00Z",
    "updated_at": "2024-10-31T00:00:00Z",
    "html_url": "",
    "pull_request_url": "https://gitea.example.co.uk/pulls/12"
  }
```

</details>

**Comment by imgurbot12** [comment]
Hey, glad to see its useful, and thanks for the bug report and the example json.

I just published a new branch called [fix/team](https://github.com/imgurbot12/prbot/tree/fix/team) that should patch the issue. The code in that branch has been tagged as v2 and a temporary release has been made to allow for use in actions testing.

Please let me know if it fixes the issue for you and I will merge those changes into master and make a more permanent release. Thanks! :)

**Comment by gitbugr** [comment]
Oh wow, that was quick! Thanks so much for the fix, It works perfectly! (:

**Comment by imgurbot12** [comment]
Happy to help and glad its working. Thanks again for the bug report.
