### ISSUE TITLE
No longer cleaning any reviews

### ISSUE THREAD

**Issue by gitbugr** [imgurbot12/prbot#2]
Hey again, have discovered an issue introduced by #1,

My apologies for lackluster testing - it did fix my issue (causing my workflows to fail.) - however, as a byproduct, the tool no longer cleans any reviews.

I believe this is because the "team" key, contains `null` for regular reviews. 

I'm not too familiar with rust, I'm guessing the acfa5076 commit is checking for the presence of the "team" key, regardless of whether it has a value or not.

**Comment by imgurbot12** [comment]
Hmm, interesting. At the time of updating I had checked a PR with only 1 bot review for its structure to see if the `team` key was always there and it had seemed like it was not nor set to null. Maybe there's a condition or state I'm not aware of.

Would you be able to post a basic description of the review process or what order the reviews were made in to help me replicate the issue please? To be honest, I wasn't aware there were such a thing as team reviews before your first issue, I'm not sure how to post one for my own testing lol.

**Comment by gitbugr** [comment]
No worries. So, to replicate, you need to create an organisation in gitea, (`https://gitea.example.com/org/create`), and create a team (`https://gitea.example.com/org/<ORG_NAME>/teams`), and add a member to it. Create a repository in that organisation, (`https://gitea.example.com/repo/create?org=<ORG_ID>`) and a pull request.

From a pull request, you can then request a review, by clicking the cog on the right hand side, and clicking one of the teams at the bottom:
![image](https://github.com/user-attachments/assets/4c9a8cd6-15cd-4692-8fa4-3b3114448dca)


In the API, that'll create a review record like the one in #1

Other review records have this structure for me:

<details><summary>Example</summary>
<p>


```json
[
  {
    "id": 913,
    "user": {
      "id": 9,
      "login": "phpstan-bot",
      "login_name": "",
      "source_id": 0,
      "full_name": "",
      "email": "phpstan@exmaple.com",
      "avatar_url": "https://gitea.example.com/avatars/abcdef123",
      "html_url": "https://gitea.example.com/phpstan-bot",
      "language": "en-US",
      "is_admin": false,
      "last_login": "2024-10-17T09:29:29Z",
      "created": "2024-10-17T09:19:34Z",
      "restricted": false,
      "active": true,
      "prohibit_login": false,
      "location": "",
      "website": "",
      "description": "",
      "visibility": "private",
      "followers_count": 0,
      "following_count": 0,
      "starred_repos_count": 0,
      "username": "phpstan-bot"
    },
    "team": null,
    "state": "PENDING",
    "body": "**Error Report from Gitea Actions [*](https://gitea.example.com/MYORG/my-repo/actions/runs/202)**\n ...",
    "commit_id": "abcdef123",
    "stale": false,
    "official": false,
    "dismissed": false,
    "comments_count": 46,
    "submitted_at": "2024-11-05T19:58:37Z",
    "updated_at": "2024-11-05T22:29:07Z",
    "html_url": "https://gitea.example.com/MYORG/my-repo/pulls/21#issuecomment-12226",
    "pull_request_url": "https://gitea.example.com/MYORG/my-repo/pulls/21"
  }
]
```

</p>
</details>

**Comment by imgurbot12** [comment]
@gitbugr thanks for the thorough explanation. It made replication and testing much easier.

Turns out your suspicions were right. It appears null values [still appear as Some](https://github.com/imgurbot12/prbot/commit/7c2712f831250de265f239729d75522ce9162de6) which was causing any and all reviews to be skipped so long as a single team review existed on record since the team field then appears for all reviews then on.

Just posted a patch and republished the v2 release. Please let me know if that works for you :)

**Comment by gitbugr** [comment]
Works for me great! Thank you again! (:
